import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowRight, Box, CheckCircle2, ChevronRight, CircleDot, Code2, Download, FileCode2, FileText, GitBranch, Layers, LoaderCircle, Radar, Search, ShieldAlert, TestTube2, Workflow} from 'lucide-react';
import './style.css';

async function api(url, body) {
  const response = await fetch(url, body === undefined ? {} : {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)});
  const data = await response.json();
  if (!response.ok) throw new Error(typeof data.detail === 'string' ? data.detail : JSON.stringify(data.detail || data));
  return data;
}
const short = path => path.split('/').pop();
function Risk({value}) {return <span className={`risk ${String(value).toLowerCase()}`}><span/>{value}</span>}

function ImpactMap({report, selected, onSelect}) {
  const groups = [[], [], []];
  report.affected.slice(0, 30).forEach(item => groups[Math.min(item.depth, 2)].push(item));
  const positions = new Map();
  groups.forEach((group, col) => group.forEach((item, row) => positions.set(item.file, {x:18+col*285, y:48+row*69})));
  const height = Math.max(190, 68 + Math.max(...groups.map(g=>g.length))*69);
  return <div className="map-scroll"><svg className="impact-map" viewBox={`0 0 860 ${height}`} role="img" aria-label="Dependency map: changed files on the left, consumers to the right">
    <defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="#54727c"/></marker></defs>
    {['CHANGE ORIGIN','DIRECT CONSUMERS','TRANSITIVE CONSUMERS'].map((text,i)=><text key={text} x={20+i*285} y="22" className="map-label">{text}</text>)}
    {report.graph.edges.map((edge,i)=>{const a=positions.get(edge.target), b=positions.get(edge.source); if(!a||!b||a.x===b.x)return null; return <path key={i} d={`M${a.x+240},${a.y+25} C${a.x+265},${a.y+25} ${b.x-25},${b.y+25} ${b.x},${b.y+25}`} fill="none" stroke="#28434e" markerEnd="url(#arrow)"/>})}
    {Array.from(positions, ([file,p])=><g key={file} className="map-node" role="button" tabIndex="0" aria-label={`Inspect ${file}`} onClick={()=>onSelect(file)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onSelect(file)}}>
      <rect x={p.x} y={p.y} width="240" height="51" rx="8" fill={selected===file?'#163937':'#121e2c'} stroke={selected===file?'#56dcb4':'#2a3b4e'}/><circle cx={p.x+15} cy={p.y+25} r="3" fill={p.x<30?'#56dcb4':'#8094be'}/>
      <text x={p.x+27} y={p.y+23} className="map-file">{short(file).slice(0,29)}</text><text x={p.x+27} y={p.y+40} className="map-directory">{file.length>35?'…'+file.slice(-34):file}</text></g>)}
  </svg>{report.affected.length>30&&<p className="muted">First 30 files visualized. The complete impact list is below.</p>}</div>
}

function App() {
  const [repository,setRepository]=useState('.'), [repo,setRepo]=useState(null), [mode,setMode]=useState('description');
  const [description,setDescription]=useState(''), [diff,setDiff]=useState(''), [file,setFile]=useState('');
  const [semantic,setSemantic]=useState(true), [llm,setLlm]=useState(true), [model,setModel]=useState('codellama');
  const [reports,setReports]=useState([]), [report,setReport]=useState(null), [job,setJob]=useState(null);
  const [watch,setWatch]=useState({enabled:false}), [error,setError]=useState(''), [selected,setSelected]=useState(''), [search,setSearch]=useState('');
  const [submitting,setSubmitting]=useState(false), [tab,setTab]=useState('impact'), [loadingRepo,setLoadingRepo]=useState(false);
  const busy = submitting || (job && ['queued','running'].includes(job.status));
  async function refreshReports() {setReports(await api('/api/reports'));}
  async function loadRepo(value=repository) {setLoadingRepo(true);setError('');try {setRepo(await api('/api/repository?repository='+encodeURIComponent(value)));}catch(e){setError(e.message)}finally{setLoadingRepo(false)}}
  async function openReport(id) {try {const data=await api('/api/reports/'+id);setReport(data);setSelected(data.changed_files[0]||'');setTab('impact')}catch(e){setError(e.message)}}
  useEffect(()=>{loadRepo();refreshReports().catch(e=>setError(e.message));api('/api/watch').then(setWatch).catch(()=>{});api('/api/jobs').then(rows=>{const active=rows.find(j=>['queued','running'].includes(j.status));if(active)setJob(active)}).catch(()=>{});},[]);
  useEffect(()=>{
    if(!job||!['queued','running'].includes(job.status))return;
    let disposed=false;
    const poll=async()=>{try{const data=await api('/api/jobs/'+job.id);if(disposed)return;setJob(data);if(data.status==='completed'){await openReport(data.report_id);await refreshReports()}else if(data.status==='failed')setError(data.message)}catch(e){if(!disposed){setError(e.message);setJob(null)}}};
    const timer=setInterval(poll,2000);return()=>{disposed=true;clearInterval(timer)};
  },[job?.id,job?.status]);
  useEffect(()=>{if(!watch.enabled)return;const timer=setInterval(async()=>{try {const status=await api('/api/watch');setWatch(status);if(status.last_job&&status.last_job!==job?.id){const latest=await api('/api/jobs/'+status.last_job);setJob(latest);if(latest.status==='completed'){await openReport(latest.report_id);await refreshReports()}}}catch(e){setError(e.message)}},5000);return()=>clearInterval(timer)},[watch.enabled,job?.id]);
  async function submit(event){event.preventDefault();setSubmitting(true);setError('');try{const request={repository,description,semantic,use_llm:llm,model,use_git:mode==='git',changed_files:mode==='file'&&file?[file]:[],diff:mode==='diff'?diff:''};setJob(await api('/api/analyses',request))}catch(e){setError(e.message)}finally{setSubmitting(false)}}
  async function toggleWatch(){try{setWatch(await api('/api/watch',{repository,enabled:!watch.enabled,semantic,use_llm:false}));setError('')}catch(e){setError(e.message)}}
  const affected=report?.affected.find(item=>item.file===selected);
  const evidence=report?.evidence.filter(item=>item.file===selected)||[];
  const visible=report?.affected.filter(item=>item.file.toLowerCase().includes(search.toLowerCase()))||[];
  return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><div className="brand-icon"><Workflow size={23}/></div><div>CodeImpact<span>AI CHANGE INTELLIGENCE</span></div></a>
    <div className="workspace-label">WORKSPACE</div><button className="nav-item active" onClick={()=>setTab('impact')}><GitBranch size={17}/>Change analysis<span className="tiny-tag">AI</span></button>
    <a className="nav-item" href="http://127.0.0.1:5050/" target="_blank" rel="noreferrer"><Layers size={17}/>RepoPilot Lab<ArrowRight size={14}/></a>
    <div className="sidebar-heading">SAVED REPORTS <span>{reports.length}</span></div>
    <div className="history">{reports.length?reports.map(item=><button key={item.id} onClick={()=>openReport(item.id)} className={'history-item '+(report?.id===item.id?'chosen':'')}><FileText size={15}/><span>{new Date(item.created_at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}<small>{item.summary.split(',')[1]?.trim()||item.summary}</small></span><i className={'dot '+item.risk?.toLowerCase()}/></button>):<p className="history-empty">Your analysis reports will appear here.</p>}</div>
    <div className="sidebar-bottom"><span className="online-dot"/>Local workspace<span className="muted">v1.0</span></div></aside>
    <div className="main"><header className="topbar"><div><span className="muted">Workspace</span><ChevronRight size={14}/><span>Change analysis</span></div><span className="local-badge"><ShieldAlert size={13}/>Local analysis · Ollama</span></header>
    <main><div className="page-heading"><div><p className="eyebrow">UNDERSTAND THE RIPPLE EFFECT</p><h1>Every change has a story.</h1><p className="subtitle">Trace dependencies, discover hidden impact, and ship with context.</p></div><button className={'watch-button '+(watch.enabled?'watching':'')} onClick={toggleWatch}><Activity size={16}/>{watch.enabled?'Watching changes':'Watch repository'}<span className={'toggle '+(watch.enabled?'on':'')}/></button></div>
      {watch.enabled&&<div className="notice">Watching {watch.repository}. Stable file changes trigger an automatic graph and retrieval report. AI review runs when you select Analyze. {watch.error&&<strong>{watch.error}</strong>}</div>}
      {error&&<div className="error" role="alert"><ShieldAlert size={17}/>{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
      <div className="workspace-grid"><section className="panel change-panel"><div className="panel-title"><div><Code2 size={18}/><h2>Describe your change</h2></div><span className="step-label">01 / INPUT</span></div>
        <form onSubmit={submit}><label className="field-label">Repository <div className="repo-input"><GitBranch size={15}/><input value={repository} onChange={e=>setRepository(e.target.value)} onBlur={()=>loadRepo()} aria-label="Repository directory"/><button type="button" onClick={()=>loadRepo()} disabled={loadingRepo}>{loadingRepo?<LoaderCircle size={14} className="spin"/>:'Load'}</button></div></label>
          <p className="field-hint">Path relative to the configured workspace. “.” analyzes this repository.</p>
          <div className="input-tabs">{[['description','Describe'],['diff','Paste diff'],['file','Select file'],['git','Git changes']].map(([value,label])=><button type="button" key={value} className={mode===value?'selected':''} onClick={()=>setMode(value)}>{label}</button>)}</div>
          {mode==='file'&&<label className="field-label">Modified file<select value={file} required onChange={e=>setFile(e.target.value)}><option value="">Choose a file…</option>{repo?.files.map(item=><option key={item.id}>{item.id}</option>)}</select></label>}
          {mode==='git'&&<div className="git-note"><GitBranch size={18}/><div><strong>Working tree vs HEAD</strong><p>Includes staged, unstaged, deleted, and untracked supported files.</p></div></div>}
          {mode==='diff'&&<textarea aria-label="Git diff or patch" className="diff-input" placeholder={'diff --git a/app/main.py b/app/main.py\n--- a/app/main.py\n+++ b/app/main.py\n@@ -1,1 +1,1 @@\n-old behavior\n+new behavior'} value={diff} onChange={e=>setDiff(e.target.value)} required spellCheck="false"/>}
          <textarea aria-label="Change description" placeholder="e.g. Change password validation rules. Which login flows, API consumers, and tests might be affected?" value={description} onChange={e=>setDescription(e.target.value)} required={mode==='description'} rows={mode==='diff'?2:5}/>
          <div className="options"><label><input type="checkbox" checked={semantic} onChange={e=>setSemantic(e.target.checked)}/>Semantic retrieval</label><label><input type="checkbox" checked={llm} onChange={e=>setLlm(e.target.checked)}/>AI reasoning</label></div>
          <div className="run-row"><select aria-label="Review model" value={model} onChange={e=>setModel(e.target.value)}><option value="codellama">Code Llama</option><option value="qwen2.5-coder">Qwen2.5 Coder</option><option value="starcoder2">StarCoder2</option></select><button className="primary" disabled={busy}>{busy?<LoaderCircle size={16} className="spin"/>:<Radar size={16}/>} {busy?'Analyzing…':'Analyze impact'} {!busy&&<ArrowRight size={15}/>}</button></div>
          <p className="privacy-note">Read-only analysis. Suggested fixes are never applied automatically.</p></form>
      </section><section className="panel overview-panel"><div className="panel-title"><div><Box size={18}/><h2>Repository overview</h2></div><span className="connected">{repo?'Connected':'Loading'}</span></div>
        <p className="repo-name">{repo?.root.split(/[\\/]/).pop()||'Repository'}<span>{repo?.root||'Reading repository…'}</span></p><div className="repo-stats"><div><strong>{repo?.files.length??'—'}</strong><span>Files in scope</span></div><div><strong>{repo?.edges??'—'}</strong><span>Dependency edges</span></div><div><strong>{repo?.files.filter(f=>f.kind==='test').length??'—'}</strong><span>Test files</span></div></div>
        <div className="pipeline"><div><span>1</span><strong>Map the change</strong><p>Parse source, imports, and references.</p></div><div><span>2</span><strong>Connect the evidence</strong><p>Trace consumers and retrieve related code.</p></div><div><span>3</span><strong>Assess the impact</strong><p>Review risks and identify regression tests.</p></div></div>
        <div className="coverage-note"><CircleDot size={14}/>{repo?.skipped.length||0} files skipped by limits. Dynamic runtime relationships may need manual review.</div></section></div>
      {busy&&<div className="job-status" role="status"><LoaderCircle size={19} className="spin"/><div><strong>{job?.message||'Submitting analysis'}</strong><span>First-time embedding can take several minutes. Cached chunks are reused.</span></div><span className="live-tag">LIVE</span></div>}
      {!report&&!busy&&<section className="panel empty-state"><div className="empty-graphic"><GitBranch size={34}/><span/><CircleDot size={20}/></div><h2>See what your next change touches.</h2><p>Select a file, describe a change, or compare your working tree.<br/>Your impact map and evidence will appear here.</p><div className="example-row"><button onClick={()=>{setMode('file');setFile('app/ollama_client.py');setDescription('Change the LLM response contract and token usage metadata.')}}>Try: LLM response contract <ArrowRight size={13}/></button><button onClick={()=>{setMode('file');setFile('ingestion/vectorstore.py');setDescription('Change the search results returned by the vector store.')}}>Try: retrieval schema <ArrowRight size={13}/></button></div></section>}
      {report&&<section className="results"><div className="result-heading"><div><p className="eyebrow">CHANGE IMPACT REPORT</p><h2>From change to consequence <Risk value={report.risk}/></h2><p className="muted">{report.summary} · {report.duration_seconds}s</p></div><a className="secondary" href={`/api/reports/${report.id}/markdown`}><Download size={15}/>Export report</a></div>
        <div className="result-stats"><div><GitBranch/><span><strong>{report.changed_files.length}</strong>Change seeds{report.inferred_seeds?' (inferred)':''}</span></div><div><Workflow/><span><strong>{report.affected.length}</strong>Affected files</span></div><div><TestTube2/><span><strong>{report.recommended_tests.length}</strong>Recommended tests</span></div><div><Search/><span><strong>{report.semantic_candidates.length}</strong>Related candidates</span></div></div>
        <div className="report-status"><span>Semantic index: <b>{report.index.status}</b></span><span>AI review: <b>{report.ai.status}</b></span><span>Snapshot: <code>{report.fingerprint.slice(0,10)}</code></span></div>
        {report.warnings.length>0&&<details className="notice"><summary>{report.warnings.length} analysis notices</summary>{report.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}
        <div className="report-tabs">{[['impact','Impact map'],['tests','Tests & fixes'],['ai','AI reasoning'],['evidence','Source evidence']].map(([value,label])=><button className={tab===value?'selected':''} key={value} onClick={()=>setTab(value)}>{label}</button>)}</div>
        {tab==='impact'&&<><section className="panel graph-panel"><div className="panel-title"><div><Workflow size={18}/><h2>Dependency impact map</h2></div><span className="muted">Click a file to inspect evidence</span></div><ImpactMap report={report} selected={selected} onSelect={setSelected}/></section>
          <div className="impact-detail-grid"><section className="panel"><div className="panel-title"><h2>Affected components</h2><input className="filter" placeholder="Filter files…" aria-label="Filter affected files" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="file-list">{visible.map(item=><button key={item.file} className={'file-row '+(selected===item.file?'chosen':'')} onClick={()=>setSelected(item.file)}><FileCode2 size={16}/><span>{item.file}<small>{item.relationship} · {item.kind}{item.deleted?' · deleted':''}</small></span><Risk value={item.risk}/><ChevronRight size={14}/></button>)}</div></section><section className="panel detail-panel"><h2>{selected||'Choose a file'}</h2>{affected&&<><div className="detail-tags"><Risk value={affected.risk}/><span className="tag">{affected.relationship}</span></div>{affected.risk_reasons.map((r,i)=><p key={i}>{r}</p>)}<h3>Why this file?</h3>{affected.path.length?affected.path.map((edge,i)=><div className="path-step" key={i}><code>{edge.source}:{edge.line}</code><span>{edge.relation} → {edge.target}{edge.revision?' (base revision)':''}</span><pre>{edge.evidence}</pre></div>):<p className="muted">{report.inferred_seeds?'A possible change location inferred from retrieval. Confirm this seed.':'Explicitly selected or detected in the Git change.'}</p>}{affected.apis.length>0&&<><h3>API surface</h3>{affected.apis.map((a,i)=><code className="api-route" key={i}>{a.method} {a.path}</code>)}</>}{affected.symbols.length>0&&<details><summary>{affected.symbols.length} symbols in scope</summary>{affected.symbols.map((s,i)=><p key={i}><code>{s.name}</code> · lines {s.start}–{s.end}</p>)}</details>}</>}</section></div>
          {report.semantic_candidates.length>0&&<section className="panel candidates"><h2>Related candidates</h2><p className="muted">These files are similar to the change but have no traced dependency path. Validate them separately.</p>{report.semantic_candidates.map(c=><div className="candidate" key={c.file}><FileText size={16}/><code>{c.file}:{c.start}</code><span>{c.retrieval}</span><b>{c.score.toFixed(3)}</b></div>)}</section>}</>}
        {tab==='tests'&&<div className="impact-detail-grid"><section className="panel"><h2>Recommended regression tests</h2><p className="muted">Suggested tests are not executed by the dashboard.</p>{report.recommended_tests.length?report.recommended_tests.map(t=><article className="test-card" key={t.file}><TestTube2 size={17}/><div><strong>{t.file}</strong><p>{t.reason}</p>{t.command&&<pre>{t.command.map(x=>x.includes(' ')?JSON.stringify(x):x).join(' ')}</pre>}</div></article>):<div className="notice">No existing tests were traced. Add regression tests for the changed behavior before merging.</div>}</section><section className="panel"><h2>Mitigation checklist</h2>{report.affected.filter(a=>a.depth===0||a.risk==='High').map(item=><article className="fix-card" key={item.file}><h3>{item.file}</h3>{item.suggestions.map((s,i)=><p key={i}><CheckCircle2 size={15}/>{s}</p>)}</article>)}</section></div>}
        {tab==='ai'&&<section className="panel"><h2>Evidence-grounded AI review</h2><p className="muted">Model: {report.ai.model||model}. Citations are checked; reasoning still requires human review. Rejected findings: {report.ai.rejected_findings||0}.</p>{report.ai.error&&<div className="notice">{report.ai.error}</div>}{report.ai.findings.length?report.ai.findings.map((f,i)=><article className="ai-finding" key={i}><div><code>{f.file}</code><Risk value={f.risk}/></div><p>{f.reasoning}</p><p className="suggestion">{f.suggestion}</p><div className="citation-row">{f.evidence_ids.map(id=>{const c=report.evidence.find(x=>x.id===id);return <button key={id} onClick={()=>{setSelected(c.file);setTab('evidence')}}>{c.file}:{c.start}–{c.end}</button>})}</div></article>):<p>No validated AI findings. The dependency map and mitigation checklist remain available.</p>}</section>}
        {tab==='evidence'&&<section className="panel"><div className="panel-title"><h2>Source evidence</h2><select aria-label="Evidence file" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">All evidence</option>{[...new Set(report.evidence.map(c=>c.file))].map(file=><option key={file}>{file}</option>)}</select></div>{(selected?evidence:report.evidence).map(c=><article className="evidence" key={c.id}><div><code>{c.file}:{c.start}–{c.end}</code><span>{c.revision||'current'}</span></div><pre>{c.text}</pre></article>)}{selected&&!evidence.length&&<p className="muted">No source excerpt selected for this file. Its reference chain is available in the impact map.</p>}</section>}
        <details className="limitations"><summary>Coverage & analysis limits</summary><p>Analyzed {report.coverage.files} files and {report.coverage.chunks} chunks. Skipped {report.coverage.skipped.length} files due to explicit limits.</p>{report.limitations.map((l,i)=><p key={i}>{l}</p>)}</details>
      </section>}
      <footer><span><GitBranch size={13}/>CodeImpact AI</span><span>Repository evidence. Traceable reasoning. Informed changes.</span></footer>
    </main></div></div>
}

createRoot(document.getElementById('root')).render(<App/>);
